//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dollar_Converter.DollarConverterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DollarConverterServiceReference.IDollarConverterService")]
    public interface IDollarConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDollarConverterService/ConvertNumberToWord", ReplyAction="http://tempuri.org/IDollarConverterService/ConvertNumberToWordResponse")]
        string ConvertNumberToWord(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDollarConverterService/ConvertNumberToWord", ReplyAction="http://tempuri.org/IDollarConverterService/ConvertNumberToWordResponse")]
        System.Threading.Tasks.Task<string> ConvertNumberToWordAsync(string number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDollarConverterServiceChannel : Dollar_Converter.DollarConverterServiceReference.IDollarConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DollarConverterServiceClient : System.ServiceModel.ClientBase<Dollar_Converter.DollarConverterServiceReference.IDollarConverterService>, Dollar_Converter.DollarConverterServiceReference.IDollarConverterService {
        
        public DollarConverterServiceClient() {
        }
        
        public DollarConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DollarConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DollarConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DollarConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConvertNumberToWord(string number) {
            return base.Channel.ConvertNumberToWord(number);
        }
        
        public System.Threading.Tasks.Task<string> ConvertNumberToWordAsync(string number) {
            return base.Channel.ConvertNumberToWordAsync(number);
        }
    }
}
